<?php

use App\Models\Langue;
use Illuminate\Support\Str;

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

$descriptions = [
    'Anglais' => "1. La langue anglaise : une clé d’accès au monde et un levier stratégique pour le Bénin\n\nL’anglais occupe une place unique dans le paysage linguistique mondial. C’est la langue de la diplomatie moderne, des grandes puissances économiques, des technologies émergentes, des sciences, du commerce international, de l’aviation, de l’informatique et des plateformes globales.\n\nPour le Bénin, l’anglais est plus qu’une simple langue étrangère :\nc’est un outil stratégique, devenu indispensable dans un environnement international où les frontières culturelles sont de plus en plus ouvertes.\n\nUn rôle capital dans l’éducation et la formation\n\nDe nombreux jeunes béninois se tournent vers l’anglais pour accéder à :\n\ndes cours universitaires internationaux ;\n\ndes conférences scientifiques ;\n\ndes certifications professionnelles ;\n\ndes ressources numériques inaccessibles en français.\n\nCela permet l’acquisition de compétences techniques modernes et renforce l’employabilité dans un marché mondial très compétitif.\n\nUne langue de voisinage indispensable\n\nLe Bénin est entouré ou proche de pays majoritairement anglophones :\nNigeria, Ghana, Libéria, Sierra Leone.\nDans les échanges transfrontaliers, commerciaux et professionnels, l’anglais devient un instrument de communication incontournable. Les commerçants, les transporteurs, les entrepreneurs, les artisans et les opérateurs économiques l’utilisent régulièrement.\n\nUn pont culturel vers le reste du monde\n\nGrâce à l’anglais, le patrimoine béninois — musique, arts, tourisme, traditions — peut être présenté à un public international. Les artistes peuvent diffuser leurs œuvres sur des plateformes mondiales, les chercheurs partager leurs résultats, et les promoteurs culturels ouvrir le Bénin à un tourisme de qualité.\n\nL’anglais ne remplace pas les langues locales ; il élargit la voix du Bénin et permet à sa culture de circuler et de rayonner à l’échelle planétaire.\nL’anglais : ouverture internationale, opportunités, évolution technologique.",
    
    'Français' => "2. La langue française : pilier de la nation, ciment social et vitrine culturelle\n\nLe français est la langue officielle du Bénin et l’un des fondements de son fonctionnement institutionnel. Son rôle dépasse largement l’administration : c’est une langue qui unifie un pays riche de dizaines de langues maternelles.\n\nUn outil de cohésion nationale\n\nLe français permet la communication entre les différentes communautés linguistiques du pays. Dans un État où coexistent plusieurs groupes ethniques et culturels, il sert de langue commune, évitant les barrières linguistiques et facilitant le dialogue national.\n\nLangue de l’école et de la pensée moderne\n\nDans le système éducatif béninois, le français est la langue de l’apprentissage, du raisonnement scientifique et de la production intellectuelle.\nC’est par lui que les élèves accèdent à :\n\nla littérature universelle ;\n\nles sciences ;\n\nle droit ;\n\nl’économie ;\n\nles technologies ;\n\nles formations professionnelles.\n\nGrâce au français, les étudiants du Bénin peuvent participer à la Francophonie, un espace mondial où circulent idées, innovations, cultures, projets et opportunités.\n\nVitrine culturelle du Bénin\n\nDe nombreux écrivains, dramaturges, cinéastes, historiens et artistes béninois utilisent le français pour exprimer leur créativité. Ils y racontent :\n\nles traditions du royaume du Danxomè ;\n\nl’histoire politique du pays ;\n\nles musiques traditionnelles ;\n\nles légendes et les identités régionales ;\n\nles transformations de la société moderne.\n\nAinsi, le français devient un instrument permettant de porter la culture béninoise hors de ses frontières tout en renforçant le dialogue entre les cultures du monde francophone.\nLe français : unité nationale, instruction, modernité institutionnelle.",
    
    'Fon' => "🪘 3. La langue fon : cœur culturel, mémoire historique et racines profondes du Bénin\n\nLe fon est l’une des langues les plus emblématiques du Bénin. Héritée du royaume du Danxomè, elle reste un pilier linguistique et culturel, particulièrement dans le sud du pays (Abomey, Ouidah, Bohicon, Cotonou, Porto-Novo).\n\nUne langue porteuse d’histoire\n\nLe fon conserve la mémoire des anciens royaumes, des rois et reines, des Amazones, des rituels, des batailles et des coutumes ancestrales.\nOn y trouve :\n\ndes récits royaux richement transmis ;\n\ndes généalogies ;\n\ndes proverbes philosophiques ;\n\ndes contes traditionnels ;\n\ndes chants rituels.\n\nChaque mot fon porte une nuance, un vécu, une émotion. La langue a une beauté poétique particulière qui donne de la force aux histoires, aux chants et aux cérémonies.\n\nUne langue vivante dans les pratiques culturelles\n\nLe fon est au centre :\n\ndes danses traditionnelles (tchinkounmè, zinli, gogbahoun…) ;\n\ndes musiques rituelles vodun ;\n\ndes festivals ;\n\ndu théâtre populaire ;\n\ndes cérémonies familiales ;\n\nde l’art oratoire ;\n\ndes bénédictions et des salutations codifiées.\n\nIl donne corps à l’identité du sud béninois et continue de structurer la vie sociale quotidienne, des conversations dans les marchés aux réunions familiales.\n\nUn symbole d’identité et de continuité\n\nDans une société moderne en transformation, le fon demeure un repère pour les jeunes. Il leur permet de :\n\ncomprendre leur héritage ;\n\nhonorer les traditions ;\n\nmaintenir le lien intergénérationnel ;\n\nrenforcer la diversité linguistique nationale.\n\nLe fon n’est pas seulement parlé : il est vécu, incarné, transmis et célébré. C’est l’une des grandes richesses du Bénin."
];

foreach ($descriptions as $name => $desc) {
    $lang = Langue::where('nom_langue', $name)->first();
    
    if ($lang) {
        $lang->description = $desc;
        $lang->save();
        echo "Updated $name\n";
    } else {
        echo "Language $name not found.\n";
    }
}
